app = "composing-studio"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 3030
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 65536
    soft_limit = 1024

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls"]
    tls_options = { alpn = ["h2", "http/1.1"] }

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
