name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest

      - run: wasm-pack build cstudio-wasm

      - run: npm ci

      - run: npx eslint --max-warnings 0 src

      - run: npm run build

  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm ci --only=dev

      - run: npx prettier --check .

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo fmt -- --check
